version: "3.3"
services:
  jenkins:
    image: gnoguchi/jenkins
    ports:
      - "8888:8080"
    volumes:
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/jenkins:/var/jenkins_home"
  customer-node-app:
    image: gnoguchi/simplenodeapp
    ports:
      - "3000:3000"
  sonarqube:
    image: sonarqube:7.1
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/sonarqube/extensions:/opt/sonarqube/extensions"
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/sonarqube/data:/opt/sonarqube/data"
  arachni:
    image: gnoguchi/arachni
    ports:
      - "9292:9292"
  owasp-dependency-check:
    volumes:
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/owasp-dependency-check/data:/usr/share/dependency-check/data"
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/owasp-dependency-check/report:/report"
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/owasp-dependency-check/src:/src"