version: "3.3"
services:
  jenkins:
    image: gnoguchi/jenkins
    ports:
      - "8888:8080"
    volumes:
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/jenkins:/var/jenkins_home"
  sonarqube:
    image: sonarqube:7.1
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/sonarqube/extensions:/opt/sonarqube/extensions"
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/sonarqube/data:/opt/sonarqube/data"
  arachni:
    image: gnoguchi/arachni
    ports:
      - "9292:9292"
  owasp-dependency-check:
    image: owasp/dependency-check
    volumes:
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/owasp-dependency-check/data:/usr/share/dependency-check/data"
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/owasp-dependency-check/report:/report"
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/owasp-dependency-check/src:/src"
  rancher-server:
    image: rancher/server:v1.6.8
    ports:
      - "8080:8080"
  rancher-agent:
    image: rancher/agent:v1.2.6
    volumes:
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/rancher/sock:/var/run/docker.sock"
      - "/home/gabriel/Documentos/repositorio/estudos/devops/projeto-devsecops-ci/volumes/rancher/lib-rancher:/var/lib/rancher"
    environment:
      - CATTLE_HOST_LABELS='group=nodeapp'