version: "3.3"
services:
  jenkins:
    image: gnoguchi/jenkins
    ports:
      - "8888:8080"
    volumes:
      - "/home/gabriel/Documents/repositorio/estudos/projeto-ci-devsecops/volumes/jenkins:/var/jenkins_home"
  sonarqube:
    image: sonarqube:7.1
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - "/home/gabriel/Documents/repositorio/estudos/projeto-ci-devsecops/volumes/sonarqube/extensions:/opt/sonarqube/extensions"
      - "/home/gabriel/Documents/repositorio/estudos/projeto-ci-devsecops/volumes/sonarqube/data:/opt/sonarqube/data"
  arachni:
    image: gnoguchi/arachni
    ports:
      - "9292:9292"
  owasp-dependency-check:
    image: owasp/dependency-check
    volumes:
      - "/home/gabriel/Documents/repositorio/estudos/projeto-ci-devsecops/volumes/owasp-dependency-check/data:/usr/share/dependency-check/data"
      - "/home/gabriel/Documents/repositorio/estudos/projeto-ci-devsecops/volumes/owasp-dependency-check/report:/report"
      - "/home/gabriel/Documents/repositorio/estudos/projeto-ci-devsecops/volumes/owasp-dependency-check/src:/src"
  rancher-server:
    image: rancher/server:v1.6.14
    ports:
      - "8080:8080"
    volumes:
      - "/home/gabriel/Documents/repositorio/estudos/projeto-ci-devsecops/volumes/rancher/server-mysql:/var/lib/mysql"